/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockToken__factory } from "./MockToken__factory";
export { SalaryManager__factory } from "./SalaryManager__factory";
